apiVersion: v2
name: pdvd
description: Post-Deployment Vulnerability Detection and AI Remediation
home: https://ortelius.io
icon: https://ortelius.github.io/pdvd-charts/ortelius.svg
keywords:
- Vulnerability
- Remediation
- AI
- SBOM
type: application
version: 12.0.109
appVersion: 12.0.0
dependencies:
- name: pdvd-arangodb
  version: 12.0.14
  repository: https://ortelius.github.io/pdvd-arangodb/
- name: pdvd-backend
  version: 12.0.326
  repository: https://ortelius.github.io/pdvd-backend/
- name: pdvd-frontend
  version: 12.0.1546
  repository: https://ortelius.github.io/pdvd-frontend/
- name: pdvd-osvdev-job
  version: 12.0.192
  repository: https://ortelius.github.io/pdvd-osvdev-job/
